### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by JSEHV** [Rikujolla/oontoissa#1]
As you created a nice app, it deserves a nice icon that fits the Sailfish OS design style. I created for you an icon that reflects the core of the app, the daily working times registration. Hope you appreciate the effort.

![harbour-atwork-green-172x172](https://user-images.githubusercontent.com/5128988/50171836-d8da3b80-02f3-11e9-8398-c65dff31b3b1.png)
![harbour-atwork-orange-172x172](https://user-images.githubusercontent.com/5128988/50171839-da0b6880-02f3-11e9-97bc-70385baf0c03.png)

There is also a background image to go on the cover page (as many apps have). An examples of the implementation can be found eg. here:

https://github.com/accumulator/Quickddit/blob/master/sailfish/qml/cover/CoverPage.qml

All sizes:

[harbour-atwork.zip](https://github.com/Rikujolla/oontoissa/files/2691614/harbour-atwork.zip)

**Comment by Rikujolla** [comment]
Thanks for your effort! I will join this to my app definitely. Thanks. Which colour you prefer? Green or orange?

**Comment by JSEHV** [comment]
I prefer orange, gives it more punch. But hey, if you prefer the green, go ahead. It is your app in the end :)

**Comment by Rikujolla** [comment]
I'll take orange. I would like to add your name to contributions. How do you like it to be presented? The proposal is "App icon (JSEHV)"

**Comment by JSEHV** [comment]
That's fine. Thanks :)

**Comment by Rikujolla** [comment]
New icon published in the versions Harbour, OpenRepos and Mer OBS. Thanks for JSEHV!
